// https://nuxt.com/docs/api/configuration/nuxt-config
import Aura from '@primeuix/themes/aura';
export default defineNuxtConfig({
    compatibilityDate: '2025-07-15',
    devtools: {
        enabled: true
    },
    modules: ['@primevue/nuxt-module', '@nuxtjs/tailwindcss'],
    ssr: false,
    app: {
        head: {
            title: 'Sakai Nuxt',
            link: [
                { rel: 'stylesheet', href: 'https://fonts.cdnfonts.com/css/lato' },
                { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
            ]
        }
    },
    css: ['primeicons/primeicons.css', '~/assets/css/styles.scss'],
    primevue: {
        options: {
            theme: {
                preset: Aura,
                options: {
                    darkModeSelector: '.app-dark'
                }
            }
        }
    },
    vite: {
        optimizeDeps: {
            include: [

        'primevue/config',
        '@vue/devtools-core',
        '@vue/devtools-kit',
        '@primeuix/themes',
        '@primeuix/themes/aura',
        '@primeuix/themes/lara',
        '@primeuix/themes/nora',
        'primevue/styleclass',
        'primevue/accordion',
        'primevue/accordioncontent',
        'primevue/accordionheader',
        'primevue/accordionpanel',
        'primevue/accordiontab',
        'primevue/animateonscroll',
        'primevue/autocomplete',
        'primevue/avatar',
        'primevue/avatargroup',
        'primevue/badge',
        'primevue/badgedirective',
        'primevue/blockui',
        'primevue/breadcrumb',
        'primevue/button',
        'primevue/buttongroup',
        'primevue/calendar',
        'primevue/card',
        'primevue/carousel',
        'primevue/cascadeselect',
        'primevue/checkbox',
        'primevue/checkboxgroup',
        'primevue/chart',
        'primevue/chip',
        'primevue/chips',
        'primevue/colorpicker',
        'primevue/column',
        'primevue/columngroup',
        'primevue/confirmationeventbus',
        'primevue/confirmationservice',
        'primevue/confirmdialog',
        'primevue/confirmpopup',
        'primevue/contextmenu',
        'primevue/datatable',
        'primevue/dataview',
        'primevue/datepicker',
        'primevue/deferredcontent',
        'primevue/dialog',
        'primevue/dialogservice',
        'primevue/divider',
        'primevue/dock',
        'primevue/drawer',
        'primevue/dropdown',
        'primevue/dynamicdialog',
        'primevue/dynamicdialogeventbus',
        'primevue/fieldset',
        'primevue/fileupload',
        'primevue/floatlabel',
        'primevue/fluid',
        'primevue/focustrap',
        'primevue/galleria',
        'primevue/iconfield',
        'primevue/iftalabel',
        'primevue/image',
        'primevue/imagecompare',
        'primevue/inlinemessage',
        'primevue/inplace',
        'primevue/inputchips',
        'primevue/inputgroup',
        'primevue/inputgroupaddon',
        'primevue/inputicon',
        'primevue/inputmask',
        'primevue/inputnumber',
        'primevue/inputotp',
        'primevue/inputswitch',
        'primevue/inputtext',
        'primevue/keyfilter',
        'primevue/knob',
        'primevue/listbox',
        'primevue/megamenu',
        'primevue/menu',
        'primevue/menubar',
        'primevue/message',
        'primevue/metergroup',
        'primevue/multiselect',
        'primevue/orderlist',
        'primevue/organizationchart',
        'primevue/overlaybadge',
        'primevue/overlayeventbus',
        'primevue/overlaypanel',
        'primevue/paginator',
        'primevue/panel',
        'primevue/panelmenu',
        'primevue/password',
        'primevue/picklist',
        'primevue/popover',
        'primevue/portal',
        'primevue/progressbar',
        'primevue/progressspinner',
        'primevue/radiobutton',
        'primevue/radiobuttongroup',
        'primevue/rating',
        'primevue/ripple',
        'primevue/row',
        'primevue/scrollpanel',
        'primevue/scrolltop',
        'primevue/select',
        'primevue/selectbutton',
        'primevue/sidebar',
        'primevue/skeleton',
        'primevue/slider',
        'primevue/speeddial',
        'primevue/splitbutton',
        'primevue/splitter',
        'primevue/splitterpanel',
        'primevue/step',
        'primevue/stepitem',
        'primevue/steplist',
        'primevue/steppanel',
        'primevue/steppanels',
        'primevue/stepper',
        'primevue/steps',
        'primevue/tab',
        'primevue/tablist',
        'primevue/tabmenu',
        'primevue/tabpanel',
        'primevue/tabpanels',
        'primevue/tabs',
        'primevue/tabview',
        'primevue/tag',
        'primevue/terminal',
        'primevue/terminalservice',
        'primevue/textarea',
        'primevue/tieredmenu',
        'primevue/timeline',
        'primevue/toast',
        'primevue/toasteventbus',
        'primevue/toastservice',
        'primevue/togglebutton',
        'primevue/toggleswitch',
        'primevue/toolbar',
        'primevue/tooltip',
        'primevue/tree',
        'primevue/treeselect',
        'primevue/treetable',
        'primevue/virtualscroller',            
            ]
        }
    }
});
